#pragma once

#include <Arduino.h>

const char WEB_INTERFACE_HTML[] PROGMEM = 
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "<meta charset=\"UTF-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no\">\n"
  "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n"
  "<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n"
  "<meta name=\"theme-color\" content=\"#060606\">\n"
  "<link rel=\"manifest\" href=\"/manifest.json\">\n"
  "<title>Marauder</title>\n"
  "<style>\n"
  ":root{--bg:#060606;--s:#111;--b:#222;--t:#ddd;--d:#888;--g:#0c6;--r:#f44;--y:#fa0;--a:#0c6;--rd:8px;--nav-h:52px}\n"
  "*{box-sizing:border-box;margin:0;padding:0}\n"
  "body{font:14px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--bg);color:var(--t);padding:0 0 var(--nav-h) 0;max-width:100vw;overflow-x:hidden}\n"
  ".page{display:none;padding:10px 12px;padding-bottom:calc(var(--nav-h)+20px)}\n"
  ".page.active{display:block}\n"
  "nav{position:fixed;bottom:0;left:0;right:0;height:var(--nav-h);background:var(--s);border-top:1px solid var(--b);display:flex;z-index:50}\n"
  "nav button{flex:1;background:none;border:none;color:var(--d);font-size:20px;cursor:pointer;transition:.15s;padding:4px 0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px}\n"
  "nav button span{font-size:9px;text-transform:uppercase;letter-spacing:.3px}\n"
  "nav button.active{color:var(--a)}\n"
  "nav button:active{opacity:.6}\n"
  ".topbar{display:flex;align-items:center;justify-content:space-between;padding:8px 0 10px;position:sticky;top:0;background:var(--bg);z-index:10;border-bottom:1px solid var(--b);margin-bottom:10px}\n"
  ".topbar h1{font-size:1em;font-weight:600;letter-spacing:.5px}\n"
  ".topbar .dot{width:8px;height:8px;border-radius:50%;background:var(--r);display:inline-block}\n"
  ".topbar .dot.ok{background:var(--g)}\n"
  ".section{background:var(--s);border:1px solid var(--b);border-radius:var(--rd);padding:10px;margin-bottom:8px}\n"
  ".section h2{font-size:.72em;color:var(--d);text-transform:uppercase;letter-spacing:.5px;margin-bottom:8px}\n"
  ".row{display:flex;gap:4px;flex-wrap:wrap;margin-bottom:4px}\n"
  ".btn{padding:6px 10px;border:1px solid var(--b);border-radius:var(--rd);background:var(--s);color:var(--t);font:inherit;font-size:.7em;cursor:pointer;transition:.12s;white-space:nowrap}\n"
  ".btn:hover{border-color:var(--a);color:var(--a)}\n"
  ".btn:active{background:var(--a);color:var(--bg)}\n"
  ".btn.ac{border-color:var(--a);color:var(--a)}\n"
  ".btn.dg{border-color:var(--r);color:var(--r)}.btn.dg:hover{background:var(--r);color:var(--bg)}\n"
  ".btn.wn{border-color:var(--y);color:var(--y)}\n"
  ".btn.xs{padding:3px 7px;font-size:.65em}\n"
  "table{width:100%;border-collapse:collapse;font-size:.68em;margin-top:4px}\n"
  "th,td{padding:3px 5px;text-align:left;border-bottom:1px solid var(--b)}\n"
  "th{color:var(--d);font-weight:400;text-transform:uppercase;font-size:.8em}\n"
  "tr:hover{background:rgba(255,255,255,.025)}\n"
  "tr.sel{background:rgba(0,204,102,.1)}\n"
  ".badge{display:inline-block;padding:1px 5px;border-radius:3px;font-size:.7em;background:var(--b)}\n"
  ".scroll{max-height:220px;overflow-y:auto}\n"
  "input,select{background:var(--bg);border:1px solid var(--b);border-radius:4px;color:var(--t);padding:5px 8px;font:inherit;font-size:.72em;width:100%;max-width:200px}\n"
  "input:focus,select:focus{outline:none;border-color:var(--a)}\n"
  ".statgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(100px,1fr));gap:6px}\n"
  ".stat{font-size:.7em}.stat .l{color:var(--d);font-size:.6em;text-transform:uppercase}.stat .v{font-weight:600;font-size:1.05em}.v.ok{color:var(--g)}.v.er{color:var(--r)}.v.wn{color:var(--y)}\n"
  ".toast{position:fixed;top:8px;right:8px;background:var(--g);color:var(--bg);padding:6px 12px;border-radius:var(--rd);font-size:.75em;z-index:99;animation:fade .2s;pointer-events:none}\n"
  ".toast.er{background:var(--r)}.toast.wn{background:var(--y);color:var(--bg)}\n"
  "@keyframes fade{from{opacity:0;transform:translateY(-6px)}to{opacity:1;transform:translateY(0)}}\n"
  ".offline{display:none;position:fixed;top:0;left:0;right:0;background:var(--r);color:#fff;text-align:center;padding:4px;font-size:.65em;font-weight:600;z-index:100}\n"
  ".offline.show{display:block}\n"
  ".modal{display:none;position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.85);z-index:60;padding:20px;overflow-y:auto}\n"
  ".modal.show{display:flex;align-items:flex-start;justify-content:center}\n"
  ".modal>div{background:var(--s);border:1px solid var(--b);border-radius:var(--rd);padding:14px;max-width:400px;width:100%;margin-top:40px}\n"
  ".modal h3{font-size:.85em;margin-bottom:10px;color:var(--t)}\n"
  ".modal .close{float:right;background:none;border:none;color:var(--d);font-size:1.2em;cursor:pointer}\n"
  ".opbar{display:none;position:sticky;top:0;left:0;right:0;background:var(--s);border-bottom:1px solid var(--b);padding:6px 12px;z-index:40;font-size:.78em}\n"
  ".opbar.show{display:flex;align-items:center;gap:8px;flex-wrap:wrap}\n"
  ".opbar .pulse{width:8px;height:8px;border-radius:50%;background:var(--g);animation:blink 1s infinite}\n"
  ".opbar .pfx{color:var(--d);font-size:.72em}\n"
  ".opbar .sts.run{color:var(--g);font-weight:600;text-transform:uppercase;letter-spacing:.5px;font-size:.8em}\n"
  ".opbar .wc{font-size:.72em;padding:1px 6px;border-radius:3px}\n"
  ".opbar .wc.avail{color:var(--g);border:1px solid var(--g)}\n"
  ".opbar .wc.unavail{color:var(--r);border:1px solid var(--r)}\n"
  ".opbar .cnt{color:var(--y);font-variant-numeric:tabular-nums;font-weight:600}\n"
  ".opbar .stopbtn{padding:2px 8px;border:1px solid var(--r);border-radius:var(--rd);background:none;color:var(--r);font:inherit;font-size:.72em;cursor:pointer}\n"
  "@keyframes blink{50%{opacity:.25}}\n"
  ".disr{border:1px dashed var(--r) !important}\n"
  ".dopt{padding:6px 10px;border:1px solid var(--b);border-radius:var(--rd);background:var(--bg);color:var(--t);font:inherit;font-size:.75em;cursor:pointer;text-align:left;width:100%}\n"
  ".dopt:hover{border-color:var(--a)}\n"
  ".dopt.warn{color:var(--r)}\n"
  ".dconfirm{display:flex;gap:6px;margin-top:12px}\n"
  ".dconfirm .btn{flex:1}\n"
  ".btn.dg2{background:var(--r);border-color:var(--r);color:#000;font-weight:600}\n"
  ".color-picker{display:flex;gap:8px;align-items:center;flex-wrap:wrap}\n"
  ".color-picker input[type=color]{width:36px;height:36px;border:1px solid var(--b);border-radius:4px;cursor:pointer;background:var(--bg);padding:2px}\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div class=\"offline\" id=\"offlineBar\">OFFLINE — reconnecting…</div>\n"
  "<div class=\"opbar\" id=\"opBar\"><span class=\"pulse\"></span><span class=\"sts run\">RUNNING</span><span class=\"pfx\" id=\"opName\">—</span><span class=\"cnt\" id=\"opCount\"></span><span class=\"wc\" id=\"opWC\">Web Control: …</span><button class=\"stopbtn\" id=\"opStop\" onclick=\"opStopNow()\">STOP</button></div>\n"
  "<div class=\"modal\" id=\"disruptModal\">\n"
  "<div>\n"
  "<button class=\"close\" onclick=\"closeDisrupt()\">✕</button>\n"
  "<h3>⚠ Disconnects Web UI</h3>\n"
  "<div style=\"font-size:.78em;color:var(--d);margin-bottom:10px\" id=\"disruptMsg\">Management connection will be lost while this runs.</div>\n"
  "<div style=\"font-size:.7em;color:var(--d);text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px\">Auto-stop timer</div>\n"
  "<div id=\"disruptOptions\" style=\"display:flex;flex-direction:column;gap:4px\"></div>\n"
  "<div class=\"dconfirm\">\n"
  "<button class=\"btn\" onclick=\"closeDisrupt()\">CANCEL</button>\n"
  "<button class=\"btn dg2\" id=\"disruptGo\">START ANYWAY</button>\n"
  "</div>\n"
  "</div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== PAGE: STATUS ====== -->\n"
  "<div class=\"page active\" id=\"page-status\">\n"
  "<div class=\"topbar\"><h1>⚡ Marauder</h1><span class=\"dot\" id=\"connDot\"></span></div>\n"
  "<div class=\"statgrid\" id=\"statusGrid\"></div>\n"
  "<div class=\"section\"><h2>Quick Actions</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn ac\" onclick=\"api('POST','/api/scan/start?type=all')\">Scan All</button>\n"
  "<button class=\"btn dg\" onclick=\"api('POST','/api/scan/stop')\">Stop</button>\n"
  "<button class=\"btn dg\" onclick=\"api('POST','/api/attack/stop')\">Stop Atk</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/clearlist?list=ap')\">Clear APs</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/clearlist?list=sta')\">Clear Sta</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/clearlist?list=ble')\">Clear BLE</button>\n"
  "<button class=\"btn\" onclick=\"navTo('settings');api('POST','/api/reboot')\">Reboot</button>\n"
  "</div></div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== PAGE: WIFI SCAN ====== -->\n"
  "<div class=\"page\" id=\"page-wifi\">\n"
  "<div class=\"topbar\"><h1>📡 WiFi</h1><span class=\"dot\" id=\"wifiDot\"></span></div>\n"
  "<div class=\"section\"><h2>Scans</h2>\n"
  "<div class=\"row\" id=\"scanBtns\"></div></div>\n"
  "<div class=\"section\"><h2>Channel</h2>\n"
  "<div class=\"row\">\n"
  "<select id=\"chSelect\" onchange=\"api('POST','/api/channel?ch='+this.value)\"><option>1</option></select>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/channel?hop=1')\">Hop</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/channel?hop=0')\">Stop Hop</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>Lists</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/save?list=ap');toast('APs saved')\">Save APs</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/save?list=sta');toast('Stations saved')\">Save Sta</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/load?list=ap');toast('APs loaded')\">Load APs</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/load?list=sta');toast('Stations loaded')\">Load Sta</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/ssid?action=gen')\">Gen SSIDs</button>\n"
  "<button class=\"btn dg\" onclick=\"api('POST','/api/ssid?action=clear')\">Clear SSIDs</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>MAC Spoof</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/mac?type=randap')\">Rand AP</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/mac?type=randsta')\">Rand Sta</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/mac?type=cloneap')\">Clone AP</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/mac?type=clonesta')\">Clone Sta</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/mac?type=revert')\">Revert</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>AP List</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn xs\" onclick=\"loadAPs()\">Refresh</button>\n"
  "<button class=\"btn xs\" onclick=\"api('POST','/api/clearlist?list=ap')\">Clear</button>\n"
  "<button class=\"btn xs\" onclick=\"selAllAPs()\">Select All</button>\n"
  "<button class=\"btn xs\" onclick=\"api('POST','/api/ap/select?clear=1')\">Deselect</button>\n"
  "<button class=\"btn xs ac\" id=\"joinBtn\" onclick=\"joinSelAP()\">Join WiFi</button>\n"
  "</div>\n"
  "<div class=\"scroll\"><table><thead><tr><th>#</th><th>SSID</th><th>BSSID</th><th>Ch</th><th>RSSI</th><th>Sec</th><th>WPS</th><th>Sel</th></tr></thead><tbody id=\"apBody\"></tbody></table></div>\n"
  "</div>\n"
  "<div class=\"section\"><h2>Stations</h2>\n"
  "<div class=\"scroll\"><table><thead><tr><th>#</th><th>MAC</th><th>AP</th><th>Pkts</th><th>Sel</th></tr></thead><tbody id=\"staBody\"></tbody></table></div>\n"
  "</div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== PAGE: ATTACKS ====== -->\n"
  "<div class=\"page\" id=\"page-attack\">\n"
  "<div class=\"topbar\"><h1>⚔️ Attacks</h1></div>\n"
  "<div class=\"section\"><h2>WiFi Attacks</h2>\n"
  "<div class=\"row\" id=\"atkDeauth\"></div>\n"
  "<div class=\"row\" style=\"margin-top:6px\" id=\"atkBeacon\"></div>\n"
  "<div class=\"row\" style=\"margin-top:6px\" id=\"atkOther\"></div></div>\n"
  "<div class=\"section\"><h2>Scanning Attacks</h2>\n"
  "<div class=\"row\" id=\"atkScan\"></div></div>\n"
  "<div class=\"section\"><h2>Wardrive & Foxhunt</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn wn disr\" onclick=\"confirmDisrupt('Wardrive','+MODE.WARDRIVE+')\">Wardrive Start ⚠</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/wardrive?action=stop')\">Wardrive Stop</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/upload?dest=wigle')\">Upload Wigle</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/upload?dest=wdg')\">Upload WDG</button>\n"
  "</div>\n"
  "<div class=\"row\" style=\"margin-top:4px\">\n"
  "<button class=\"btn wn disr\" onclick=\"confirmDisrupt('Foxhunt','+MODE.SIG_STREN+')\">Foxhunt WiFi ⚠</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/foxhunt?band=bt')\">Foxhunt BT</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>Packet Stats</h2>\n"
  "<div id=\"rawStats\" style=\"font-size:.7em;display:flex;flex-wrap:wrap;gap:8px\"></div></div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== PAGE: BLUETOOTH ====== -->\n"
  "<div class=\"page\" id=\"page-bt\">\n"
  "<div class=\"topbar\"><h1>🔵 Bluetooth</h1></div>\n"
  "<div class=\"section\"><h2>BLE Scan</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/scan?type=airtag')\">Airtag</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/scan?type=flipper')\">Flipper</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/scan?type=flock')\">Flock</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/scan?type=meta')\">Meta</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/scan?type=skim')\">Skimmer</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>BLE Spam</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/bt/spam?type=sourapple')\">SourApple</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/bt/spam?type=applejuice')\">AppleJuice</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/bt/spam?type=swiftpair')\">SwiftPair</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/bt/spam?type=google')\">Google</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/bt/spam?type=samsung')\">Samsung</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/bt/spam?type=windows')\">Windows</button>\n"
  "<button class=\"btn wn\" onclick=\"api('POST','/api/bt/spam?type=all')\">ALL</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>FindMy</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/findmy?action=scan')\">Scan</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/findmy?action=sound&tag_index=0')\">Sound #0</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/findmy?action=sound&tag_index=1')\">Sound #1</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/bt/findmy?action=sound&tag_index=2')\">Sound #2</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>BLE Devices</h2>\n"
  "<div class=\"scroll\"><table><thead><tr><th>#</th><th>Name</th><th>MAC</th><th>RSSI</th></tr></thead><tbody id=\"bleBody\"></tbody></table></div>\n"
  "</div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== PAGE: EVIL PORTAL ====== -->\n"
  "<div class=\"page\" id=\"page-portal\">\n"
  "<div class=\"topbar\"><h1>🔑 Evil Portal</h1></div>\n"
  "<div class=\"section\"><h2>Controls</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn wn disr\" onclick=\"confirmDisrupt('Evil Portal','+MODE.EVILPORTAL+')\">Start Portal ⚠</button>\n"
  "<button class=\"btn dg\" onclick=\"api('POST','/api/evilportal?action=stop')\">Stop</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/evilportal?action=status')\">Status</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/evilportal?action=ack')\">Gen ACK</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/evilportal?action=reset')\">Reset Creds</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>Configuration</h2>\n"
  "<div class=\"row\">\n"
  "<input id=\"apName\" placeholder=\"AP Name\" value=\"FreeWiFi\">\n"
  "<button class=\"btn\" onclick=\"epStart()\">Apply</button>\n"
  "</div>\n"
  "<div class=\"row\" style=\"margin-top:4px\">\n"
  "<select id=\"htmlFile\"><option>index.html</option></select>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/evilportal?action=sethtml&html='+document.getElementById('htmlFile').value)\">Set HTML</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>Status</h2>\n"
  "<div id=\"epStatus\" style=\"font-size:.7em;color:var(--d)\">Not started</div></div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== PAGE: GPS ====== -->\n"
  "<div class=\"page\" id=\"page-gps\">\n"
  "<div class=\"topbar\"><h1>🌍 GPS</h1></div>\n"
  "<div class=\"section\"><h2>Live Data</h2>\n"
  "<div class=\"statgrid\" id=\"gpsGrid\"></div></div>\n"
  "<div class=\"section\"><h2>Tracker</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/gps/tracker?action=start')\">Start</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/gps/tracker?action=stop')\">Stop</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/wardrive?action=poi&label='+(prompt('POI label')||'checkpoint'))\">Tag POI</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>Raw NMEA</h2>\n"
  "<div class=\"scroll\" style=\"max-height:100px\"><pre id=\"nmeaOut\" style=\"font-size:.6em;color:var(--d);white-space:pre-wrap\"></pre></div>\n"
  "</div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== PAGE: SETTINGS ====== -->\n"
  "<div class=\"page\" id=\"page-settings\">\n"
  "<div class=\"topbar\"><h1>⚙️ Settings</h1></div>\n"
  "<div class=\"section\"><h2>System</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn dg\" onclick=\"if(confirm('Reboot ESP32?'))api('POST','/api/reboot')\">Reboot</button>\n"
  "<button class=\"btn\" onclick=\"loadSettings()\">Load Settings</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/settings?save=1')\">Save</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>LED</h2>\n"
  "<div class=\"row\">\n"
  "<div class=\"color-picker\">\n"
  "<input type=\"color\" id=\"ledColor\" value=\"#00cc66\"><button class=\"btn\" onclick=\"api('POST','/api/led?action=color&hex='+document.getElementById('ledColor').value)\">Set</button>\n"
  "</div></div>\n"
  "<div class=\"row\" style=\"margin-top:4px\">\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/led?action=rainbow')\">Rainbow</button>\n"
  "<button class=\"btn\" onclick=\"api('POST','/api/led?action=off')\">Off</button>\n"
  "</div></div>\n"
  "<div class=\"section\"><h2>Settings</h2>\n"
  "<div class=\"scroll\" id=\"settingsList\"></div></div>\n"
  "<div class=\"section\"><h2>SD Files</h2>\n"
  "<div class=\"row\">\n"
  "<button class=\"btn xs\" onclick=\"loadFiles()\">Refresh</button>\n"
  "<button class=\"btn xs\" onclick=\"uploadFile()\">Upload</button>\n"
  "</div>\n"
  "<div id=\"fileList\" style=\"font-size:.68em;margin-top:4px\"></div>\n"
  "</div>\n"
  "</div>\n"
  "\n"
  "<!-- ====== NAV ====== -->\n"
  "<nav>\n"
  "<button class=\"active\" onclick=\"navTo('status')\">📊<span>Status</span></button>\n"
  "<button onclick=\"navTo('wifi')\">📡<span>WiFi</span></button>\n"
  "<button onclick=\"navTo('attack')\">⚔️<span>Attack</span></button>\n"
  "<button onclick=\"navTo('bt')\">🔵<span>BT</span></button>\n"
  "<button onclick=\"navTo('portal')\">🔑<span>Portal</span></button>\n"
  "<button onclick=\"navTo('gps')\">🌍<span>GPS</span></button>\n"
  "<button onclick=\"navTo('settings')\">⚙️<span>Settings</span></button>\n"
  "</nav>\n"
  "<div id=\"toast\"></div>\n"
  "\n"
  "<script>\n"
  "// --- State ---\n"
  "var IS_ONLINE=false,OFFLINE_SINCE=0,currentPage='status';\n"
  "\n"
  "// --- Navigation ---\n"
  "function navTo(p){\n"
  "  currentPage=p;\n"
  "  document.querySelectorAll('.page').forEach(function(x){x.classList.remove('active')});\n"
  "  document.querySelectorAll('nav button').forEach(function(x){x.classList.remove('active')});\n"
  "  document.getElementById('page-'+p).classList.add('active');\n"
  "  var navBtn=document.querySelector('nav button[onclick=\"navTo(\\''+p+'\\')\"]');\n"
  "  if(navBtn)navBtn.classList.add('active');\n"
  "  if(p==='wifi')loadAPs();\n"
  "  if(p==='bt')loadBLE();\n"
  "  if(p==='gps')loadGPS();\n"
  "  if(p==='settings')loadSettings();\n"
  "  if(p==='attack')loadRawStats();\n"
  "  if(p==='portal')loadEPStatus();\n"
  "}\n"
  "\n"
  "// --- Toast ---\n"
  "function toast(msg,err){\n"
  "  var t=document.getElementById('toast');t.className='toast'+(err?' '+err:'');\n"
  "  t.textContent=msg;clearTimeout(t._t);t._t=setTimeout(function(){t.textContent=''},2000)\n"
  "}\n"
  "\n"
  "// --- API ---\n"
  "async function api(method,path,body){\n"
  "  if(!IS_ONLINE){toast('Offline','er');return null}\n"
  "  try{\n"
  "    var opts={method:method,signal:AbortSignal.timeout(8000)};\n"
  "    if(body){opts.headers={'Content-Type':'application/json'};opts.body=JSON.stringify(body)}\n"
  "    var res=await fetch(path,opts);\n"
  "    if(!res.ok)throw new Error('HTTP '+res.status);\n"
  "    return await res.json()\n"
  "  }catch(e){\n"
  "    if(IS_ONLINE)setOffline();\n"
  "    return null\n"
  "  }\n"
  "}\n"
  "function setOffline(){if(IS_ONLINE){IS_ONLINE=false;OFFLINE_SINCE=Date.now();document.getElementById('offlineBar').classList.add('show')}}\n"
  "function setOnline(){if(!IS_ONLINE){IS_ONLINE=true;document.getElementById('offlineBar').classList.remove('show');toast('Reconnected!')}}\n"
  "\n"
  "// --- Connection check ---\n"
  "async function checkConn(){\n"
  "  try{var r=await fetch('/api/status',{signal:AbortSignal.timeout(4000)});if(r.ok){setOnline();return true}}catch(e){}\n"
  "  setOffline();return false\n"
  "}\n"
  "\n"
  "// --- Disruptive-op confirmation + OP bar state ---\n"
  "var _op={running:false,name:'',impact:'safe',management_available:true,timeout_ms:0,remaining_ms:0,stop_method:'',remote_stop:true};\n"
  "var _pendingOp=null;\n"
  "var _timerPresets=[[30,'30 seconds'],[60,'1 minute'],[300,'5 minutes'],[600,'10 minutes'],[0,'No timer — manual reset required']];\n"
  "var _selTimer=60;\n"
  "function fmtT(ms){if(ms===undefined||ms===null||ms<=0)return'';var s=Math.ceil(ms/1000);var h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;function p(x){return(x<10?'0':'')+x}return(h>0?h+':'+p(m)+':'+p(sec):p(m)+':'+p(sec))}\n"
  "function renderOpBar(){\n"
  "  var b=document.getElementById('opBar');\n"
  "  if(!_op.running){b.classList.remove('show');return}\n"
  "  b.classList.add('show');\n"
  "  document.getElementById('opName').textContent=_op.name||'—';\n"
  "  var wc=document.getElementById('opWC');\n"
  "  if(_op.management_available){wc.textContent='Web Control: AVAILABLE';wc.className='wc avail'}\n"
  "  else{wc.textContent='Web Control: UNAVAILABLE';wc.className='wc unavail'}\n"
  "  var c=document.getElementById('opCount');\n"
  "  if(_op.timeout_ms>0&&_op.remaining_ms>0){c.textContent='Auto-stop in '+fmtT(_op.remaining_ms)}\n"
  "  else if(_op.timeout_ms>0&&_op.remaining_ms===0){c.textContent='Stopping…'}\n"
  "  else{c.textContent=''}\n"
  "  var s=document.getElementById('opStop');\n"
  "  s.style.display=(_op.remote_stop||_op.management_available)?'inline-block':'none';\n"
  "}\n"
  "async function opStopNow(){await api('POST','/api/operation/stop');setTimeout(loadStatus,300)}\n"
  "function confirmDisrupt(label,mode,type){\n"
  "  if(_op.running){toast('Already running: '+_op.name,'wn');return}\n"
  "  _pendingOp={label:label,mode:mode,type:type};\n"
  "  _selTimer=60;\n"
  "  document.getElementById('disruptMsg').innerHTML='<b>'+label+'</b> will tear down the management AP. Web control will be <b>lost</b> until it stops or the timer restores it.';\n"
  "  buildTimerOptions();\n"
  "  document.getElementById('disruptModal').classList.add('show');\n"
  "}\n"
  "function buildTimerOptions(){\n"
  "  document.getElementById('disruptOptions').innerHTML=_timerPresets.map(function(t){var active=(t[0]===_selTimer);var warn=(t[0]===0);return'<button class=\"dopt'+(warn?' warn':'')+'\" style=\"'+(active?'border-color:var(--a);color:var(--a)':'')+'\" onclick=\"selTimer('+t[0]+')\">'+t[1]+'</button>'}).join('');\n"
  "  document.getElementById('disruptGo').onclick=function(){\n"
  "    if(_selTimer===0){if(!confirm('No auto-stop. You must manually reset the device to regain control. Continue?'))return}\n"
  "    goDisrupt();\n"
  "  };\n"
  "}\n"
  "function selTimer(v){_selTimer=v;buildTimerOptions()}\n"
  "function closeDisrupt(){document.getElementById('disruptModal').classList.remove('show');_pendingOp=null}\n"
  "async function goDisrupt(){\n"
  "  var p=_pendingOp;closeDisrupt();\n"
  "  if(!p)return;\n"
  "  var q='?mode='+p.mode+'&duration='+(_selTimer*1000);\n"
  "  var d=await api('POST','/api/operation/start'+q);\n"
  "  if(d&&d.state==='rejected'){toast('Rejected: '+(d.reason||'?'),'er');return}\n"
  "  toast(p.label+' started','wn');\n"
  "}\n"
  "var scanNames={0:'Idle',1:'Probe',2:'AP',3:'PWN',4:'EAPOL',5:'DeauthSniff',6:'All',7:'Packet',8:'BeaconSpam',9:'Rickroll',12:'ESP',15:'BeaconList',16:'TargetAP',18:'Auth',19:'Mimic',20:'Deauth',21:'APSpam',22:'TgtAPFull',23:'ActEAPOL',25:'Raw',26:'Station',29:'Foxhunt',30:'EvilPortal',31:'GPS',32:'Wardrive',36:'SourApple',46:'ChanAnalyzer',48:'PktRate',50:'PineScan',51:'MultiSSID',56:'BadMSG',61:'Sleep',82:'AppleJuice'};\n"
  "\n"
  "async function loadStatus(){\n"
  "  var d=await api('GET','/api/status');if(!d)return;\n"
  "  var h='<div class=\"stat\"><div class=\"l\">Version</div><div class=\"v\">'+d.version+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Board</div><div class=\"v\">'+d.hardware+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">WiFi</div><div class=\"v '+(d.wifi_connected?'ok':'er')+'\">'+(d.wifi_connected?'Connected':d.wifi_ap_mode?'AP Mode':'Off')+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Scan</div><div class=\"v\">'+(scanNames[d.current_scan]||d.current_scan)+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Channel</div><div class=\"v\">'+d.channel+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">APs</div><div class=\"v ok\">'+(d.ap_count||0)+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Stations</div><div class=\"v\">'+(d.station_count||0)+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">BLE</div><div class=\"v\">'+(d.ble_count||0)+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">SSIDs</div><div class=\"v\">'+(d.ssid_count||0)+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Heap</div><div class=\"v\">'+Math.round((d.free_heap||0)/1024)+'KB</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Uptime</div><div class=\"v\">'+Math.round((d.uptime_ms||0)/1000)+'s</div></div>';\n"
  "  if(d.battery_pct!==undefined)h+='<div class=\"stat\"><div class=\"l\">Battery</div><div class=\"v\">'+d.battery_pct+'%</div></div>';\n"
  "  if(d.gps_has_fix)h+='<div class=\"stat\"><div class=\"l\">GPS</div><div class=\"v ok\">Fixed</div></div>';\n"
  "  document.getElementById('statusGrid').innerHTML=h||'<span style=\"color:var(--r)\">OFFLINE</span>';\n"
  "  if(d.operation){_op=d.operation}\n"
  "  renderOpBar();\n"
  "  if(d.wifi_connected){document.getElementById('connDot').classList.add('ok');try{document.getElementById('wifiDot').classList.add('ok')}catch(e){}}\n"
  "  else{document.getElementById('connDot').classList.remove('ok');try{document.getElementById('wifiDot').classList.remove('ok')}catch(e){}}\n"
  "}\n"
  "\n"
  "// --- WiFi page ---\n"
  "var MODE={AP:2,STA:26,ALL:6,PROBE:1,PWN:3,DEAUTH:5,EAPOL:4,RAW:25,BEACON:16,PACKET:7,SAE:77,PINESCAN:50,MULTISSID:51,DEAUTH_ATTACK:20,DEAUTH_TARGETED:27,BEACON_SPAM:8,BEACON_LIST:15,RICKROLL:9,PROBE_SPAM:21,BADMSG:56,SLEEP:61,MIMIC:19,EVILPORTAL:30,WARDRIVE:32,SOURAPPLE:36,APPLEJUICE:82,SWIFTPAIR:37,SPAM_ALL:38,SAMSUNG:39,GOOGLE:41,FLIPPER_SPAM:42,AIRTAG_SPOOF:44,FINDMY:86,SKIMMER:11};\n"
  "(function buildWifiPage(){\n"
  "  var scans=[['AP',MODE.AP],['Station',MODE.STA],['All',MODE.ALL],['Probe',MODE.PROBE],['PWN',MODE.PWN],['DeauthSniff',MODE.DEAUTH],['EAPOL',MODE.EAPOL],['Raw',MODE.RAW],['Beacon',MODE.BEACON],['Packet',MODE.PACKET],['SAE',MODE.SAE],['PineScan',MODE.PINESCAN],['MultiSSID',MODE.MULTISSID]];\n"
  "  document.getElementById('scanBtns').innerHTML=scans.map(function(s){return'<button class=\"btn xs disr\" onclick=\"confirmDisrupt(\''+s[0]+'\','+s[1]+')\">'+s[0]+' ⚠</button>'}).join('');\n"
  "  \n"
  "  // Channel selector\n"
  "  var ch='';for(var i=1;i<=14;i++)ch+='<option value=\"'+i+'\">Ch '+i+'</option>';\n"
  "  document.getElementById('chSelect').innerHTML=ch;\n"
  "\n"
  "  // Attack buttons  \n"
  "  document.getElementById('atkDeauth').innerHTML='<button class=\"btn dg disr\" onclick=\"confirmDisrupt(\'Deauth\','+MODE.DEAUTH_ATTACK+')\">Deauth ⚠</button><button class=\"btn dg disr\" onclick=\"confirmDisrupt(\'Deauth Manual\','+MODE.DEAUTH_ATTACK+')\">Deauth Manual ⚠</button>';\n"
  "  document.getElementById('atkBeacon').innerHTML='<button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Beacon Spam\','+MODE.BEACON_SPAM+')\">Beacon Spam ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Beacon List\','+MODE.BEACON_LIST+')\">Beacon List ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Rickroll\','+MODE.RICKROLL+')\">Rickroll ⚠</button>';\n"
  "  document.getElementById('atkOther').innerHTML='<button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Probe Spam\','+MODE.PROBE_SPAM+')\">Probe ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'BadMSG\','+MODE.BADMSG+')\">BadMSG ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'SAE\','+MODE.SAE+')\">SAE ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Mimic\','+MODE.MIMIC+')\">CSA ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Sleep\','+MODE.SLEEP+')\">Quiet ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'AP Spam\','+MODE.PROBE_SPAM+')\">AP Spam ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Mimic\','+MODE.MIMIC+')\">Mimic ⚠</button>';\n"
  "  document.getElementById('atkScan').innerHTML='<button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Ping Scan\','+MODE.ALL+')\">Ping Scan ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Port Scan\','+MODE.ALL+')\">Port Scan ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'MAC Track\','+MODE.STA+')\">MAC Track ⚠</button><button class=\"btn wn disr\" onclick=\"confirmDisrupt(\'Karma\','+MODE.MIMIC+')\">Karma ⚠</button>';\n"
  "})();\n"
  "\n"
  "// --- Data loaders ---\n"
  "async function loadAPs(){\n"
  "  var d=await api('GET','/api/data/ap');if(!d||!d.access_points)return;\n"
  "  document.getElementById('apBody').innerHTML=d.access_points.map(function(a,i){\n"
  "    return'<tr class=\"'+(a.selected?'sel':'')+'\" onclick=\"toggleAP('+a.index+')\"><td>'+a.index+'</td><td>'+(a.essid||'[hidden]')+'</td><td style=\"font-size:.75em\">'+a.bssid+'</td><td>'+a.channel+'</td><td style=\"color:'+(a.rssi>-50?'var(--g)':a.rssi>-70?'var(--y)':'var(--r)')+'\">'+a.rssi+'</td><td><span class=\"badge\">'+a.security+'</span></td><td>'+(a.wps?'✓':'')+'</td><td>'+(a.selected?'●':'')+'</td></tr>'\n"
  "  }).join('')\n"
  "}\n"
  "async function loadStations(){\n"
  "  var d=await api('GET','/api/data/station');if(!d||!d.stations)return;\n"
  "  document.getElementById('staBody').innerHTML=d.stations.map(function(s){return'<tr><td>'+s.index+'</td><td style=\"font-size:.75em\">'+s.mac+'</td><td>'+s.ap_index+'</td><td>'+s.packets+'</td><td>'+(s.selected?'●':'')+'</td></tr>'}).join('')\n"
  "}\n"
  "async function loadBLE(){\n"
  "  var d=await api('GET','/api/data/ble');if(!d||!d.ble_devices)return;\n"
  "  document.getElementById('bleBody').innerHTML=d.ble_devices.map(function(b){return'<tr><td>'+b.index+'</td><td>'+(b.name||'[?]')+'</td><td style=\"font-size:.75em\">'+(b.mac||'')+'</td><td>'+b.rssi+'</td></tr>'}).join('')\n"
  "}\n"
  "async function loadRawStats(){\n"
  "  var d=await api('GET','/api/data/rawstats');if(!d)return;\n"
  "  document.getElementById('rawStats').innerHTML='<span>Beacon: <b style=\"color:var(--g)\">'+(d.beacon_frames||0)+'</b></span><span>Req: <b>'+d.req_frames+'</b></span><span>Resp: <b>'+d.resp_frames+'</b></span><span>Deauth: <b style=\"color:var(--r)\">'+(d.deauth_frames||0)+'</b></span><span>EAPOL: <b style=\"color:var(--y)\">'+(d.eapol_frames||0)+'</b></span><span>Mgmt: <b>'+d.mgmt_frames+'</b></span><span>Data: <b>'+d.data_frames+'</b></span><span>BT: <b>'+d.bt_frames+'</b></span><span>Flock: <b>'+d.flock_devices+'</b></span><span>RSSI: <b>'+(d.min_rssi||0)+'/'+(d.max_rssi||0)+'</b></span><span>Ch: <b>'+d.channel+'</b></span>'\n"
  "}\n"
  "async function loadGPS(){\n"
  "  var d=await api('GET','/api/gps');if(!d||d.available===false){document.getElementById('gpsGrid').innerHTML='<div class=\"stat\"><div class=\"v\">GPS unavailable</div></div>';return}\n"
  "  var h='<div class=\"stat\"><div class=\"l\">Fix</div><div class=\"v '+(d.fix?'ok':'er')+'\">'+(d.fix?'YES':'NO')+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Lat</div><div class=\"v\">'+(d.lat||'?')+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Lon</div><div class=\"v\">'+(d.lon||'?')+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Alt</div><div class=\"v\">'+(d.alt||'?')+'m</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Sats</div><div class=\"v\">'+(d.satellites||0)+'</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">Accuracy</div><div class=\"v\">'+(d.accuracy||'?')+'m</div></div>';\n"
  "  h+='<div class=\"stat\"><div class=\"l\">UTC</div><div class=\"v\">'+(d.datetime||'?')+'</div></div>';\n"
  "  document.getElementById('gpsGrid').innerHTML=h;\n"
  "  if(d.nmea)document.getElementById('nmeaOut').textContent=d.nmea\n"
  "}\n"
  "\n"
  "// --- Settings ---\n"
  "async function loadSettings(){\n"
  "  var d=await api('GET','/api/settings');if(!d)return;\n"
  "  var h='';if(d.keys)for(var k in d.keys)h+='<div style=\"display:flex;justify-content:space-between;padding:3px 0;border-bottom:1px solid var(--b);font-size:.7em\"><span>'+k+'</span><span style=\"color:var(--a);cursor:pointer\" onclick=\"api(\\'POST\\',\\'/api/settings?key='+k+'&toggle=1\\');toast(\\'Toggled '+k+'\\')\">'+d.keys[k]+'</span></div>';\n"
  "  document.getElementById('settingsList').innerHTML=h||'<span style=\"color:var(--d)\">No settings</span>'\n"
  "}\n"
  "\n"
  "// --- Evil Portal ---\n"
  "function epStart(){\n"
  "  var apn=document.getElementById('apName').value||'FreeWiFi';\n"
  "  var html=document.getElementById('htmlFile').value||'index.html';\n"
  "  api('POST','/api/evilportal?action=start&apname='+encodeURIComponent(apn)+'&html='+encodeURIComponent(html))\n"
  "}\n"
  "async function loadEPStatus(){var d=await api('POST','/api/evilportal?action=status');if(d)document.getElementById('epStatus').innerHTML='Running: '+(d.running?'<span style=\"color:var(--g)\">YES</span>':'NO')+' | AP: '+(d.ap_name||'?')+' | Victims: '+(d.victim_count||0)}\n"
  "\n"
  "// --- File browser ---\n"
  "async function loadFiles(){\n"
  "  var d=await api('GET','/api/files');if(!d||!d.files){document.getElementById('fileList').innerHTML='<span style=\"color:var(--d)\">No SD or files</span>';return}\n"
  "  document.getElementById('fileList').innerHTML=d.files.map(function(f){return'<div style=\"display:flex;justify-content:space-between;padding:3px 0;border-bottom:1px solid var(--b);font-size:.7em\"><span>'+f+'</span><button class=\"btn xs dg\" onclick=\"if(confirm(\\'Delete '+f+'?\\'))api(\\'POST\\',\\'/api/files/delete?file='+encodeURIComponent(f)+'\\');setTimeout(loadFiles,500)\">Del</button></div>'}).join('')\n"
  "}\n"
  "function uploadFile(){\n"
  "  var inp=document.createElement('input');inp.type='file';inp.onchange=function(){\n"
  "    var f=inp.files[0];if(!f)return;\n"
  "    var fd=new FormData();fd.append('file',f);\n"
  "    fetch('/api/files/upload',{method:'POST',body:fd}).then(function(r){return r.json()}).then(function(d){toast(d.ok?'Uploaded':'Failed',d.ok?'':'er');setTimeout(loadFiles,500)})\n"
  "  };inp.click()\n"
  "}\n"
  "function selAllAPs(){api('POST','/api/ap/select?all=1')}\n"
  "function toggleAP(idx){api('POST','/api/ap/select?index='+idx+'&toggle=1')}\n"
  "function joinSelAP(){var pw=prompt('WiFi password (leave empty if open)')||'';api('POST','/api/join?pw='+encodeURIComponent(pw))}\n"
  "\n"
  "// --- Boot ---\n"
  "(async function boot(){\n"
  "  if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(function(){})}\n"
  "  IS_ONLINE=await checkConn();\n"
  "  if(IS_ONLINE){loadStatus()}else{loadStatus()}\n"
  "  setInterval(async function(){if(IS_ONLINE){loadStatus()}else{await checkConn();if(IS_ONLINE)loadStatus()}},4000);\n"
  "  setInterval(function(){if(IS_ONLINE){if(currentPage==='wifi'){loadAPs();loadStations()}if(currentPage==='bt')loadBLE();if(currentPage==='attack')loadRawStats();if(currentPage==='gps')loadGPS()}},6000);\n"
  "  \n"
  "  var dp;window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();dp=e});\n"
  "  window.installPWA=function(){if(dp){dp.prompt();dp.userChoice.then(function(){dp=null})}};\n"
  "})();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
  "\n"
;
