#pragma once
#include <pgmspace.h>

// Auto-generated: web-interface/index.html (15512 bytes)

const char WEB_INTERFACE_HTML[] PROGMEM = 
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "<meta charset=\"UTF-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\n"
  "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n"
  "<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n"
  "<meta name=\"theme-color\" content=\"#0a0a0a\">\n"
  "<link rel=\"manifest\" href=\"/manifest.json\">\n"
  "<title>Marauder</title>\n"
  "<style>\n"
  ":root{--bg:#0a0a0a;--surface:#141414;--border:#2a2a2a;--text:#e0e0e0;--dim:#888;--green:#0c6;--red:#f44;--yellow:#fa0;--accent:#0c6;--radius:8px}\n"
  "*{box-sizing:border-box;margin:0;padding:0}\n"
  "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',monospace;background:var(--bg);color:var(--text);padding:12px;max-width:800px;margin:0 auto;padding-bottom:60px}\n"
  ".offline-bar{display:none;position:fixed;top:0;left:0;right:0;background:var(--red);color:#fff;text-align:center;padding:6px;font-size:.7em;font-weight:bold;z-index:100}\n"
  ".offline-bar.show{display:block}\n"
  ".status-bar{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:12px;margin-bottom:12px;display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:8px}\n"
  ".stat{font-size:.75em}.stat .label{color:var(--dim);text-transform:uppercase;font-size:.65em}.stat .val{font-weight:bold;font-size:1.1em}.val.ok{color:var(--green)}.val.err{color:var(--red)}.val.warn{color:var(--yellow)}\n"
  ".section{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:12px;margin-bottom:12px}\n"
  ".section h2{font-size:.85em;color:var(--dim);text-transform:uppercase;margin-bottom:8px;letter-spacing:.5px}\n"
  ".row{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:6px;align-items:center}\n"
  ".btn{padding:8px 14px;border:1px solid var(--border);border-radius:var(--radius);background:var(--surface);color:var(--text);font:inherit;font-size:.78em;cursor:pointer;transition:all .15s;white-space:nowrap}\n"
  ".btn:hover{border-color:var(--accent);color:var(--accent)}\n"
  ".btn:active{background:var(--accent);color:var(--bg)}\n"
  ".btn.danger{border-color:var(--red);color:var(--red)}.btn.danger:hover{background:var(--red);color:var(--bg)}\n"
  ".btn.warn{border-color:var(--yellow);color:var(--yellow)}\n"
  ".btn.small{padding:4px 10px;font-size:.7em}\n"
  "table{width:100%;border-collapse:collapse;font-size:.72em;margin-top:6px}\n"
  "th,td{padding:4px 6px;text-align:left;border-bottom:1px solid var(--border)}\n"
  "th{color:var(--dim);font-weight:normal;text-transform:uppercase;font-size:.85em}\n"
  "tr:hover{background:rgba(255,255,255,.03)}\n"
  ".badge{display:inline-block;padding:1px 6px;border-radius:4px;font-size:.75em;background:var(--border)}\n"
  ".scroll-table{max-height:250px;overflow-y:auto}\n"
  ".toast{position:fixed;bottom:12px;right:12px;background:var(--green);color:var(--bg);padding:8px 16px;border-radius:var(--radius);font-size:.8em;z-index:99;animation:fadeIn .2s}\n"
  ".toast.err{background:var(--red)}\n"
  ".toast.warn{background:var(--yellow);color:var(--bg)}\n"
  "@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}\n"
  ".install-btn{display:none;position:fixed;bottom:12px;left:12px;background:var(--accent);color:var(--bg);border:none;padding:10px 20px;border-radius:var(--radius);font:inherit;font-size:.8em;font-weight:bold;cursor:pointer;z-index:99;box-shadow:0 2px 8px rgba(0,0,0,.4)}\n"
  ".install-btn.show{display:block}\n"
  "#rawStats{font-size:.75em;display:flex;flex-wrap:wrap;gap:10px}\n"
  "#rawStats span b{color:var(--accent)}\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "\n"
  "<div class=\"offline-bar\" id=\"offlineBar\">⚠ ESP32 OFFLINE — reconnecting...</div>\n"
  "<button class=\"install-btn\" id=\"installBtn\" onclick=\"installPWA()\">📲 Add to Home Screen</button>\n"
  "\n"
  "<div id=\"statusBar\" class=\"status-bar\"></div>\n"
  "\n"
  "<div class=\"section\"><h2>📡 Scan</h2>\n"
  "<div class=\"row\" id=\"scanBtns\"></div>\n"
  "<button class=\"btn small danger\" style=\"margin-top:4px\" onclick=\"api('POST','/api/scan/stop')\">Stop All</button>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>⚔️ Attack</h2>\n"
  "<div class=\"row\" id=\"attackBtns\"></div>\n"
  "<button class=\"btn small danger\" style=\"margin-top:4px\" onclick=\"api('POST','/api/attack/stop')\">Stop Attacks</button>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>🔵 Bluetooth</h2>\n"
  "<div class=\"row\" id=\"btBtns\"></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>🌍 GPS & Wardrive</h2>\n"
  "<div class=\"row\" id=\"gpsBtns\"></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>🔑 Evil Portal</h2>\n"
  "<div class=\"row\" id=\"epBtns\"></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>📋 AP List</h2>\n"
  "<div class=\"row\" style=\"margin-bottom:6px\">\n"
  "<button class=\"btn small\" onclick=\"loadAPs()\">Refresh</button>\n"
  "<button class=\"btn small\" onclick=\"api('POST','/api/clearlist?list=ap')\">Clear</button>\n"
  "</div>\n"
  "<div class=\"scroll-table\"><table id=\"apTable\"><thead><tr><th>#</th><th>SSID</th><th>BSSID</th><th>Ch</th><th>RSSI</th><th>Sec</th></tr></thead><tbody></tbody></table></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>📊 Stations</h2>\n"
  "<div class=\"scroll-table\"><table id=\"staTable\"><thead><tr><th>#</th><th>MAC</th><th>AP</th><th>Ch</th><th>RSSI</th></tr></thead><tbody></tbody></table></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>🟦 BLE</h2>\n"
  "<div class=\"scroll-table\"><table id=\"bleTable\"><thead><tr><th>#</th><th>Name</th><th>MAC</th><th>RSSI</th></tr></thead><tbody></tbody></table></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"section\"><h2>📈 Packet Stats</h2><div id=\"rawStats\"></div></div>\n"
  "\n"
  "<script>\n"
  "// --- Offline resilience ---\n"
  "var IS_ONLINE=false,OFFLINE_SINCE=0,RECONNECT_INTERVAL=2000;\n"
  "\n"
  "function toast(msg,err){var t=document.createElement('div');t.className='toast'+(err?' err':'');t.textContent=msg;document.body.appendChild(t);setTimeout(function(){t.remove()},2500)}\n"
  "\n"
  "async function api(method,path,body){\n"
  "  if(!IS_ONLINE){return null}\n"
  "  try{\n"
  "    var opts={method:method,signal:AbortSignal.timeout(5000)};\n"
  "    if(body){opts.headers={'Content-Type':'application/json'};opts.body=JSON.stringify(body)}\n"
  "    var res=await fetch(path,opts);\n"
  "    if(!res.ok) throw new Error('HTTP '+res.status);\n"
  "    return await res.json()\n"
  "  }catch(e){\n"
  "    if(IS_ONLINE){setOffline()} // only transition if we were online\n"
  "    return null\n"
  "  }\n"
  "}\n"
  "\n"
  "function setOffline(){\n"
  "  if(IS_ONLINE){IS_ONLINE=false;OFFLINE_SINCE=Date.now();document.getElementById('offlineBar').classList.add('show');toast('ESP32 offline — will reconnect','warn')}\n"
  "}\n"
  "function setOnline(){\n"
  "  if(!IS_ONLINE){IS_ONLINE=true;document.getElementById('offlineBar').classList.remove('show');toast('ESP32 reconnected!')}\n"
  "}\n"
  "\n"
  "async function checkConnection(){\n"
  "  try{\n"
  "    var res=await fetch('/api/status',{signal:AbortSignal.timeout(3000)});\n"
  "    if(res.ok){setOnline();return true}\n"
  "  }catch(e){}\n"
  "  setOffline();return false\n"
  "}\n"
  "\n"
  "// --- UI ---\n"
  "var scanMap={0:'Idle',2:'AP',1:'Probe',3:'PWN',4:'EAPOL',5:'DeauthSniff',6:'All',7:'Packet',8:'Beacon',9:'Rickroll',15:'BeaconList',20:'Deauth',21:'APSpam',25:'Raw',26:'Station',29:'Foxhunt',30:'EvilPortal',31:'GPS',32:'Wardrive',46:'Channel',48:'PktRate',50:'PineScan',51:'MultiSSID',56:'BadMSG',61:'Sleep'};\n"
  "\n"
  "async function loadStatus(){\n"
  "  var d=await api('GET','/api/status');\n"
  "  if(!d){fillOfflineStatus();return}\n"
  "  document.getElementById('statusBar').innerHTML=\n"
  "  '<div class=\"stat\"><div class=\"label\">Version</div><div class=\"val\">'+d.version+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">Board</div><div class=\"val\">'+d.hardware+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">WiFi</div><div class=\"val '+(d.wifi_connected?'ok':'err')+'\">'+(d.wifi_connected?'Connected':d.wifi_ap_mode?'AP Mode':'Off')+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">Scan</div><div class=\"val\">'+(scanMap[d.current_scan]||d.current_scan)+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">Ch</div><div class=\"val\">'+d.channel+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">APs</div><div class=\"val\">'+(d.ap_count||0)+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">Sta</div><div class=\"val\">'+(d.station_count||0)+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">BLE</div><div class=\"val\">'+(d.ble_count||0)+'</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">Heap</div><div class=\"val\">'+Math.round((d.free_heap||0)/1024)+'K</div></div>'+\n"
  "  (d.battery_pct!==undefined?'<div class=\"stat\"><div class=\"label\">Bat</div><div class=\"val\">'+d.battery_pct+'%</div></div>':'')+\n"
  "  (d.gps_has_fix?'<div class=\"stat\"><div class=\"label\">GPS</div><div class=\"val ok\">Fixed</div></div>':'')\n"
  "}\n"
  "function fillOfflineStatus(){\n"
  "  document.getElementById('statusBar').innerHTML=\n"
  "  '<div class=\"stat\"><div class=\"label\">Status</div><div class=\"val err\">OFFLINE</div></div>'+\n"
  "  '<div class=\"stat\"><div class=\"label\">Since</div><div class=\"val warn\">'+Math.round((Date.now()-OFFLINE_SINCE)/1000)+'s</div></div>'\n"
  "}\n"
  "\n"
  "// --- Build buttons ---\n"
  "(function(){\n"
  "  var scans=[['AP','ap'],['Station','sta'],['All','all'],['Probe','probe'],['PWN','pwn'],['DeauthSniff','deauth'],['EAPOL','eapol'],['Raw','raw'],['Beacon','beacon'],['Packet','packet'],['SAE','sae'],['PineScan','pinescan'],['MultiSSID','multissid']];\n"
  "  document.getElementById('scanBtns').innerHTML=scans.map(function(s){return '<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/scan/start?type='+s[1]+'\\');toast(\\''+s[0]+' started\\')\">'+s[0]+'</button>'}).join('');\n"
  "})();\n"
  "\n"
  "(function(){document.getElementById('attackBtns').innerHTML=\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/attack/start?type=deauth\\')\">Deauth</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/attack/start?type=beacon\\')\">BeaconSpam</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/attack/start?type=beacon&mode=list\\')\">BeaconList</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/attack/start?type=beacon&mode=rickroll\\')\">Rickroll</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/attack/start?type=probe\\')\">ProbeAtk</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/attack/start?type=badmsg\\')\">BadMSG</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/wardrive?action=start\\')\">Wardrive</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/foxhunt?band=wifi\\')\">Foxhunt</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/pingscan\\')\">PingScan</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/portscan\\')\">PortScan</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/mactrack\\')\">MACTrack</button>'+\n"
  "'<button class=\"btn small warn\" onclick=\"api(\\'POST\\',\\'/api/karma?action=start\\')\">Karma</button>';})();\n"
  "\n"
  "(function(){document.getElementById('btBtns').innerHTML=\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/bt/scan?type=airtag\\')\">BLE Scan</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/bt/spam?type=sourapple\\')\">SourApple</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/bt/spam?type=applejuice\\')\">AppleJuice</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/bt/spam?type=swiftpair\\')\">SwiftPair</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/bt/findmy?action=scan\\')\">FindMyScan</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/bt/findmy?action=sound\\')\">FindMySound</button>';})();\n"
  "\n"
  "(function(){document.getElementById('gpsBtns').innerHTML=\n"
  "'<button class=\"btn small\" onclick=\"loadGPS()\">GPS Data</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/gps/tracker?action=start\\')\">StartTracker</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/gps/tracker?action=stop\\')\">StopTracker</button>'+\n"
  "'<div id=\"gpsData\" style=\"font-size:0.7em;margin-top:6px;color:var(--dim)\"></div>';})();\n"
  "\n"
  "(function(){document.getElementById('epBtns').innerHTML=\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/evilportal?action=start\\')\">Start</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/evilportal?action=stop\\')\">Stop</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/evilportal?action=status\\')\">Status</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/evilportal?action=ack\\')\">GenAck</button>'+\n"
  "'<button class=\"btn small\" onclick=\"api(\\'POST\\',\\'/api/evilportal?action=reset\\')\">ResetCreds</button>';})();\n"
  "\n"
  "// --- Data loaders ---\n"
  "async function loadAPs(){var d=await api('GET','/api/data/ap');if(!d||!d.access_points)return;document.querySelector('#apTable tbody').innerHTML=d.access_points.map(function(a){return'<tr><td>'+a.index+'</td><td>'+(a.essid||'[hidden]')+'</td><td style=\"font-size:0.8em\">'+a.bssid+'</td><td>'+a.channel+'</td><td style=\"color:'+(a.rssi>-50?'var(--green)':a.rssi>-70?'var(--yellow)':'var(--red)')+'\">'+a.rssi+'dBm</td><td><span class=\"badge\">'+a.security+'</span></td></tr>'}).join('')}\n"
  "async function loadStations(){var d=await api('GET','/api/data/station');if(!d||!d.stations)return;document.querySelector('#staTable tbody').innerHTML=d.stations.map(function(s){return'<tr><td>'+s.index+'</td><td style=\"font-size:0.8em\">'+s.mac+'</td><td>'+s.ap_index+'</td><td>'+s.channel+'</td><td>'+s.rssi+'dBm</td></tr>'}).join('')}\n"
  "async function loadBLE(){var d=await api('GET','/api/data/ble');if(!d||!d.ble_devices)return;document.querySelector('#bleTable tbody').innerHTML=d.ble_devices.map(function(b){return'<tr><td>'+b.index+'</td><td>'+(b.name||'[?]')+'</td><td style=\"font-size:0.8em\">'+(b.mac||'')+'</td><td>'+b.rssi+'dBm</td></tr>'}).join('')}\n"
  "async function loadRawStats(){var d=await api('GET','/api/data/rawstats');if(!d)return;document.getElementById('rawStats').innerHTML='<span>Beacon: <b>'+(d.beacon_frames||0)+'</b></span><span>Probe: <b>'+(d.req_frames||0)+'</b></span><span>Deauth: <b>'+(d.deauth_frames||0)+'</b></span><span>EAPOL: <b>'+(d.eapol_frames||0)+'</b></span><span>Mgmt: <b>'+(d.mgmt_frames||0)+'</b></span><span>Data: <b>'+(d.data_frames||0)+'</b></span><span>BT: <b>'+(d.bt_frames||0)+'</b></span><span>Flock: <b>'+(d.flock_devices||0)+'</b></span><span>RSSI: <b>'+(d.min_rssi||0)+'/'+(d.max_rssi||0)+'</b></span>'}\n"
  "async function loadGPS(){var d=await api('GET','/api/gps');if(!d)return;document.getElementById('gpsData').innerHTML=d.available!==false?'Fix: '+(d.fix?'YES':'NO')+' | Lat: '+(d.lat||'?')+' | Lon: '+(d.lon||'?')+' | Alt: '+(d.alt||'?')+'m | Sat: '+(d.satellites||0)+' | Acc: '+(d.accuracy||'?')+'m':'GPS not available'}\n"
  "\n"
  "// --- Boot: register SW, check connection, start polling ---\n"
  "(async function boot(){\n"
  "  // Register Service Worker for offline caching\n"
  "  if('serviceWorker' in navigator){\n"
  "    navigator.serviceWorker.register('/sw.js').catch(function(){});\n"
  "  }\n"
  "\n"
  "  // Initial connection check\n"
  "  IS_ONLINE=await checkConnection();\n"
  "  if(IS_ONLINE){\n"
  "    loadStatus();loadAPs();loadStations();loadBLE();loadRawStats();loadGPS();\n"
  "  }else{fillOfflineStatus()}\n"
  "\n"
  "  // Status poll (critical: detects reconnect)\n"
  "  setInterval(async function(){\n"
  "    if(IS_ONLINE){loadStatus()}else{await checkConnection();if(IS_ONLINE){loadStatus();loadAPs();loadStations();loadBLE();loadRawStats();loadGPS()}}\n"
  "  },3000);\n"
  "\n"
  "  // Data poll (only when online)\n"
  "  setInterval(function(){if(IS_ONLINE){loadAPs();loadStations();loadBLE();loadRawStats();loadGPS()}},5000);\n"
  "\n"
  "  // PWA install prompt\n"
  "  var deferredPrompt;\n"
  "  window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.add('show')});\n"
  "  window.installPWA=function(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt.userChoice.then(function(r){document.getElementById('installBtn').classList.remove('show');deferredPrompt=null})}};\n"
  "})();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
  "";
